# Generated by Django 5.2.15 on 2026-06-30 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=120)),
                ('match_type', models.CharField(choices=[('contains', 'Contiene'), ('equals', 'Es igual a')], max_length=10)),
                ('kind', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categorization rule',
                'verbose_name_plural': 'categorization rules',
                'db_table': 'categorization_rules_rule',
                'ordering': ['-priority', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'pattern', 'match_type'), name='unique_active_rule_pattern_per_owner')],
            },
        ),
    ]
