# Generated by Django 5.2.16 on 2026-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='include_in_summaries',
            field=models.BooleanField(default=True),
        ),
    ]
