# Generated by Django 5.2.16 on 2026-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_include_in_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
