# Generated by Django 5.2.15 on 2026-06-30 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'source', 'external_reference'], name='transaction_account_244889_idx'),
        ),
    ]
