# Generated by Django 5.2.16 on 2026-07-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_external_reference_transaction_source_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_transfe_1c2bbf_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_group_id',
        ),
    ]
